apiVersion: v1
kind: Namespace
metadata:
  name: wpk8s
---
kind: ConfigMap
apiVersion: v1
data:
  mysql_connection: |
    DB_HOST=<INSTANCE_CONNECTION_IP>
    DB_NAME=<INSTANCE_CONNECTION_DB_NAME>
    DB_USER=<INSTANCE_CONNECTION_PORT>
  wordpress: |
    WP_HOME=http://example.com
    DB_PREFIX=wp_
    WP_ENV=production
    AUTH_KEY='<GENERATE MEEEEE>'
    SECURE_AUTH_KEY='<GENERATE MEEEEE>'
    LOGGED_IN_KEY='<GENERATE MEEEEE>'
    NONCE_KEY='<GENERATE MEEEEE>'
    AUTH_SALT='<GENERATE MEEEEE>'
    SECURE_AUTH_SALT='<GENERATE MEEEEE>'
    LOGGED_IN_SALT='<GENERATE MEEEEE>'
    NONCE_SALT='<GENERATE MEEEEE>'
metadata:
  name: wordpress-kubernetes-infrastructure
  namespace: wpk8s
  resourceVersion: "1"
---
kind: Secret
apiVersion: v1
data:
  wordpress-db-password: <Base64_ENCODED_PASSWORD>
metadata:
  name: wordpress-mysql-user-password
  namespace: wpk8s
  resourceVersion: "1"
type: Opaque