apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    project: wordpress-kubernetes-infrastructure   
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      project: wordpress-kubernetes-infrastructure  
  template:
    metadata:
      labels:
        app: nginx
        project: wordpress-kubernetes-infrastructure  
    spec:
      initContainers:
      - name: clone-repo-buid-structure
        image: k4izen/php:latest
        command: ["/bin/bash", "-c", "git clone --single-branch -- https://github.com/k4izen/wordpress-kubernetes-infrastructure.git /PROJECT && cd /PROJECT/wordpress && composer install --no-interaction --optimize-autoloader --no-dev"]
        volumeMounts:
        - name: wpdata
          mountPath: /PROJECT
      containers:
      - name: nginx
        image: k4izen/nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REDIS_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: wordpress-kubernetes-infrastructure
              key: redis_connection
        volumeMounts:
        - name: wpdata
          mountPath: /PROJECT
      volumes:
      - name: wpdata
        emptyDir: {}